/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.engagement.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class EegRaw implements org.apache.thrift.TBase<EegRaw, EegRaw._Fields>, java.io.Serializable, Cloneable, Comparable<EegRaw> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("EegRaw");

  private static final org.apache.thrift.protocol.TField MILLISECOND_TIME_STAMP_FIELD_DESC = new org.apache.thrift.protocol.TField("millisecondTimeStamp", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField RAW_FIELD_DESC = new org.apache.thrift.protocol.TField("raw", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new EegRawStandardSchemeFactory());
    schemes.put(TupleScheme.class, new EegRawTupleSchemeFactory());
  }

  public String millisecondTimeStamp; // optional
  public int raw; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MILLISECOND_TIME_STAMP((short)1, "millisecondTimeStamp"),
    RAW((short)2, "raw");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MILLISECOND_TIME_STAMP
          return MILLISECOND_TIME_STAMP;
        case 2: // RAW
          return RAW;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __RAW_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.MILLISECOND_TIME_STAMP,_Fields.RAW};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MILLISECOND_TIME_STAMP, new org.apache.thrift.meta_data.FieldMetaData("millisecondTimeStamp", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , "Timestamp")));
    tmpMap.put(_Fields.RAW, new org.apache.thrift.meta_data.FieldMetaData("raw", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(EegRaw.class, metaDataMap);
  }

  public EegRaw() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public EegRaw(EegRaw other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetMillisecondTimeStamp()) {
      this.millisecondTimeStamp = other.millisecondTimeStamp;
    }
    this.raw = other.raw;
  }

  public EegRaw deepCopy() {
    return new EegRaw(this);
  }

  @Override
  public void clear() {
    this.millisecondTimeStamp = null;
    setRawIsSet(false);
    this.raw = 0;
  }

  public String getMillisecondTimeStamp() {
    return this.millisecondTimeStamp;
  }

  public EegRaw setMillisecondTimeStamp(String millisecondTimeStamp) {
    this.millisecondTimeStamp = millisecondTimeStamp;
    return this;
  }

  public void unsetMillisecondTimeStamp() {
    this.millisecondTimeStamp = null;
  }

  /** Returns true if field millisecondTimeStamp is set (has been assigned a value) and false otherwise */
  public boolean isSetMillisecondTimeStamp() {
    return this.millisecondTimeStamp != null;
  }

  public void setMillisecondTimeStampIsSet(boolean value) {
    if (!value) {
      this.millisecondTimeStamp = null;
    }
  }

  public int getRaw() {
    return this.raw;
  }

  public EegRaw setRaw(int raw) {
    this.raw = raw;
    setRawIsSet(true);
    return this;
  }

  public void unsetRaw() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __RAW_ISSET_ID);
  }

  /** Returns true if field raw is set (has been assigned a value) and false otherwise */
  public boolean isSetRaw() {
    return EncodingUtils.testBit(__isset_bitfield, __RAW_ISSET_ID);
  }

  public void setRawIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __RAW_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MILLISECOND_TIME_STAMP:
      if (value == null) {
        unsetMillisecondTimeStamp();
      } else {
        setMillisecondTimeStamp((String)value);
      }
      break;

    case RAW:
      if (value == null) {
        unsetRaw();
      } else {
        setRaw((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MILLISECOND_TIME_STAMP:
      return getMillisecondTimeStamp();

    case RAW:
      return Integer.valueOf(getRaw());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MILLISECOND_TIME_STAMP:
      return isSetMillisecondTimeStamp();
    case RAW:
      return isSetRaw();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof EegRaw)
      return this.equals((EegRaw)that);
    return false;
  }

  public boolean equals(EegRaw that) {
    if (that == null)
      return false;

    boolean this_present_millisecondTimeStamp = true && this.isSetMillisecondTimeStamp();
    boolean that_present_millisecondTimeStamp = true && that.isSetMillisecondTimeStamp();
    if (this_present_millisecondTimeStamp || that_present_millisecondTimeStamp) {
      if (!(this_present_millisecondTimeStamp && that_present_millisecondTimeStamp))
        return false;
      if (!this.millisecondTimeStamp.equals(that.millisecondTimeStamp))
        return false;
    }

    boolean this_present_raw = true && this.isSetRaw();
    boolean that_present_raw = true && that.isSetRaw();
    if (this_present_raw || that_present_raw) {
      if (!(this_present_raw && that_present_raw))
        return false;
      if (this.raw != that.raw)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(EegRaw other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMillisecondTimeStamp()).compareTo(other.isSetMillisecondTimeStamp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMillisecondTimeStamp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.millisecondTimeStamp, other.millisecondTimeStamp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRaw()).compareTo(other.isSetRaw());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRaw()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.raw, other.raw);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("EegRaw(");
    boolean first = true;

    if (isSetMillisecondTimeStamp()) {
      sb.append("millisecondTimeStamp:");
      if (this.millisecondTimeStamp == null) {
        sb.append("null");
      } else {
        sb.append(this.millisecondTimeStamp);
      }
      first = false;
    }
    if (isSetRaw()) {
      if (!first) sb.append(", ");
      sb.append("raw:");
      sb.append(this.raw);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class EegRawStandardSchemeFactory implements SchemeFactory {
    public EegRawStandardScheme getScheme() {
      return new EegRawStandardScheme();
    }
  }

  private static class EegRawStandardScheme extends StandardScheme<EegRaw> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, EegRaw struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MILLISECOND_TIME_STAMP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.millisecondTimeStamp = iprot.readString();
              struct.setMillisecondTimeStampIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RAW
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.raw = iprot.readI32();
              struct.setRawIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, EegRaw struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.millisecondTimeStamp != null) {
        if (struct.isSetMillisecondTimeStamp()) {
          oprot.writeFieldBegin(MILLISECOND_TIME_STAMP_FIELD_DESC);
          oprot.writeString(struct.millisecondTimeStamp);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetRaw()) {
        oprot.writeFieldBegin(RAW_FIELD_DESC);
        oprot.writeI32(struct.raw);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class EegRawTupleSchemeFactory implements SchemeFactory {
    public EegRawTupleScheme getScheme() {
      return new EegRawTupleScheme();
    }
  }

  private static class EegRawTupleScheme extends TupleScheme<EegRaw> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, EegRaw struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMillisecondTimeStamp()) {
        optionals.set(0);
      }
      if (struct.isSetRaw()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetMillisecondTimeStamp()) {
        oprot.writeString(struct.millisecondTimeStamp);
      }
      if (struct.isSetRaw()) {
        oprot.writeI32(struct.raw);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, EegRaw struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.millisecondTimeStamp = iprot.readString();
        struct.setMillisecondTimeStampIsSet(true);
      }
      if (incoming.get(1)) {
        struct.raw = iprot.readI32();
        struct.setRawIsSet(true);
      }
    }
  }

}

